### PR TITLE
CI: Fix failure

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik Currently the reference tests fail as follows:
```bash
compiler_tester.tester.RunException: Testing with reference output failed.
subroutine4.f90 * ast_openmp
The JSON metadata differs against reference results
Reference JSON: tests/reference/ast_openmp-subroutine4-0411983.json
Output JSON:    tests/output/ast_openmp-subroutine4-0411983.json
Omitting 6 identical items
Differing items:
{'stdout': None} != {'stdout': 'ast_openmp-subroutine4-0411983.stdout'}
{'stderr_hash': '0175afb13d2c8f5eb228b3c9094d9fc33dab10c59e43195e0277b8a1'} != {'stderr_hash': None}
{'returncode': 127} != {'returncode': 0}
{'stderr': 'ast_openmp-subroutine4-0411983.stderr'} != {'stderr': None}
{'stdout_hash': None} != {'stdout_hash': 'bfc588ec282e44ae729cf232795342f3381ef3dc2725b5641be40f23'}No output stdout_hash available for subroutine4.f90
```

I think it fails because the `ast_openmp` uses `"cpptranslate --show-ast-openmp {infile}"` and I think the `cpptranslate` binary is unavailable. Does `conda install -c conda-forge lfortran` also install `cpptranslate`?

How would you advise to fix this? Shall we distribute `cpptranslate` along with `lfortran` in the conda-forge? Or Shall we skip testing the reference tests depending on `cpptranslate`?

**Comment by certik** [comment]
Skip `cpptranslate`. We should remove that binary. `lfortran --show-cpp` should be able to do the same thing, and if not, then just skip the tests.

**Comment by certik** [comment]
You'll have to also skip LLVM tests, since the result depends on LLVM version and each platform has a different LLVM version inside the conda package.

**Comment by Shaikh-Ubaid** [comment]
>Skip cpptranslate. We should remove that binary. lfortran --show-cpp should be able to do the same thing, and if not, then just skip the tests.

It seems `cpptranslate` (with the flag `--show-ast-openmp`) converts `fortran` code to `fortran` with parallel loops using `openmp`. Shall I send a PR to remove the above `cpptranslate` binary (and associated source files)?

**Comment by certik** [comment]
Let's just ignore this for now, as things might break, and also we don't have a replacement yet, and I think we will soon be tackling these parallel loops anyway, so we'll create a good replacement and use the `cpptranslate --show-ast-openmp` as inspiration. So let's keep it there. But just don't test it in this repository.

**Pull request merged**
