### PR TITLE
Remove things we do not want to test

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik The scipy test passes on ubuntu which we also test at the lfortran repository. The scipy test fails on macos, which I think we do not test at the lfortran repository.

**Comment by Shaikh-Ubaid** [comment]
@certik I would like to request your review on this. Please feel free to squash merge this PR.

**Comment by Shaikh-Ubaid** [comment]
I included test for `dftatom` as well in this PR.

**Comment by certik** [comment]
It looks like scipy doesn't work on macOS. So I would skip the test there.

**Review by certik — COMMENTED** [review]
I think this looks good. We need to disable scipy on macos, so that everything passes. Then we can merge.

**Pull request merged**
