### PR TITLE
Test third party packages

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran-conda-testing/issues/7

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This tests only on ubuntu for now. We can later add macos.

**Comment by Shaikh-Ubaid** [comment]
For [Temporarily test fpm on linux only](https://github.com/lfortran/lfortran-conda-testing/pull/10/commits/34ca8e11461a8b7a0ad5c526c6c1c30f4a98fa85), see https://github.com/lfortran/lfortran-conda-testing/issues/11.

**Comment by Shaikh-Ubaid** [comment]
I am merging this for now. I will work on further changes in a new PR.

**Comment by Shaikh-Ubaid** [comment]
>This tests only on ubuntu for now. We can later add macos.

We test third party packages on macos as well (excluding fpm, for now).

**Comment by certik** [comment]
Perfect! What we need now is to cleanup the build of these packages to use the original build system, or some cleaner way of building them, since that is our "documentation" and "supported way" to build the packages. Eventually we want to converge towards being as simple or simpler than other compilers.

**Pull request merged**
